### ISSUE TITLE
Screenshots Please

### ISSUE THREAD

**Issue by Noitidart** [fanqfanh/react-native-sparkline#13]
May you please add screenshots (ideally GIF) of this in action in readme? That's the first thing a lot of RN package searchers do. There are so many packages its not easy to (1) install each one, (2) then render it respecting properties, (3) then uninstall it if it doesn't fit.

**Comment by arniu** [comment]
Sorry, I'm really too busy to do it. Would you like to add some? Maybe we **together** can make it an awesome library 😄

**Comment by Noitidart** [comment]
I haven't used this yet, as I don't know what it really offers without seeing pictures. But sure ok, when I get some time, I'll install it and try to use it per Readme, I'm not sure what the end result is supposed to look like. Will screenshot what I get.

**Comment by vijayst** [comment]
I will be interested to help you out with this. Does it work for Android as well?

**Comment by arniu** [comment]
@vijayst Yes! Thanks very much 😄

**Comment by vijayst** [comment]
Screenshot for iOS
![simulator screen shot - iphone 8 - 2018-04-21 at 06 41 04](https://user-images.githubusercontent.com/3457565/39078929-0c5ad466-452f-11e8-8569-75b8e76729d8.png)

**Comment by arniu** [comment]
@vijayst Awesome! Can you make a PR to add this screenshot? Thanks very much.

**Comment by vijayst** [comment]
ok sure, I will do a PR. And android screenshot is 
![screenshot_1524275476](https://user-images.githubusercontent.com/3457565/39079284-e3a8a376-4534-11e8-8bcf-29b1a300ba86.png)

**Comment by vijayst** [comment]
Added PR!

**Comment by Noitidart** [comment]
Thanks so much @vijayst
