### ISSUE TITLE
Is there any link command for the project?

### ISSUE THREAD

**Issue by vijayst** [fanqfanh/react-native-sparkline#15]
When I use react-native-sparkline after doing `yarn install react-native-sparkline`, I get the following error:

![simulator screen shot - iphone 8 - 2018-04-22 at 08 10 16](https://user-images.githubusercontent.com/3457565/39090732-a1df91fe-4604-11e8-987b-47856d99ee16.png)

**Comment by arniu** [comment]
You should [link ART to your project](https://github.com/tomauty/react-native-chart) at first.

**Comment by arniu** [comment]
No, ART has already been enabled on Android.
