### ISSUE TITLE
How do I adjust the width of the SparkLine component?

### ISSUE THREAD

**Issue by vijayst** [fanqfanh/react-native-sparkline#17]
After drawing the sample Sparkline, it extends the width of my View. How do I constraint the width to my View or specify a width to the Sparkline?

![screen shot 2018-04-23 at 12 12 49 pm](https://user-images.githubusercontent.com/3457565/39110691-c0ec33f4-46ef-11e8-8c3b-58532f68b129.png)

**Comment by arniu** [comment]
You set `width` of `Sparkline`. 

Here is `Sparkline.defaultProps`: 

https://github.com/fanqfanh/react-native-sparkline/blob/2543a0f14ec23456f2d5100be197e16961c29e91/src/Sparkline.js#L66-L74
